tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed": "#001f26",
              "primary-fixed": "#eaddff",
              "surface-container-high": "#272a2c",
              "tertiary-fixed-dim": "#c2c6db",
              "inverse-surface": "#e0e3e5",
              "on-primary-fixed": "#25005a",
              "on-tertiary": "#2b3040",
              "error-container": "#93000a",
              "secondary-fixed": "#acedff",
              "tertiary": "#c2c6db",
              "on-surface": "#e0e3e5",
              "surface-bright": "#363a3b",
              "on-secondary-fixed-variant": "#004e5c",
              "secondary": "#4cd7f6",
              "on-tertiary-container": "#e1e5fb",
              "on-background": "#e0e3e5",
              "secondary-fixed-dim": "#4cd7f6",
              "on-tertiary-fixed": "#161b2b",
              "tertiary-fixed": "#dee1f7",
              "surface-container-lowest": "#0b0f10",
              "primary": "#d2bbff",
              "inverse-primary": "#732ee4",
              "background": "#101415",
              "secondary-container": "#03b5d3",
              "surface": "#101415",
              "on-tertiary-fixed-variant": "#414658",
              "surface-variant": "#323537",
              "inverse-on-surface": "#2d3133",
              "surface-container-highest": "#323537",
              "primary-container": "#7c3aed",
              "tertiary-container": "#616679",
              "surface-container": "#1d2022",
              "surface-dim": "#101415",
              "on-error": "#690005",
              "surface-tint": "#d2bbff",
              "outline": "#958da1",
              "on-secondary": "#003640",
              "error": "#ffb4ab",
              "on-error-container": "#ffdad6",
              "on-primary": "#3f008e",
              "on-primary-fixed-variant": "#5a00c6",
              "on-primary-container": "#ede0ff",
              "surface-container-low": "#191c1e",
              "on-surface-variant": "#ccc3d8",
              "on-secondary-container": "#00424e",
              "outline-variant": "#4a4455",
              "primary-fixed-dim": "#d2bbff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "lg": "2.5rem",
              "xl": "4rem",
              "base": "4px",
              "md": "1.5rem",
              "sm": "1rem",
              "container-max": "1280px",
              "xs": "0.5rem",
              "gutter": "24px"
      },
      "fontFamily": {
              "headline-lg-mobile": ["Space Grotesk"],
              "body-lg": ["Inter"],
              "headline-lg": ["Space Grotesk"],
              "display-lg": ["Space Grotesk"],
              "caption": ["Inter"],
              "body-md": ["Inter"],
              "label-md": ["Inter"],
              "headline-md": ["Space Grotesk"]
      },
      "fontSize": {
              "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "caption": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}]
      }
    },
  },
}
